services:
  ezlauncher-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ezlauncher-site
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
      - DOWNLOAD_URL=${DOWNLOAD_URL}
      - BLOCKMAP_URL=${BLOCKMAP_URL}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
