server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
  add_header X-Frame-Options SAMEORIGIN always;

  location = /download {
    return 302 https://github.com/ddloads/ezlauncher-site/releases/download/v0.2.0/EZlauncher%20Setup%200.2.0.exe;
  }

  location = /download/blockmap {
    return 302 https://github.com/ddloads/ezlauncher-site/releases/download/v0.2.0/EZlauncher%20Setup%200.2.0.exe.blockmap;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
